-- Trips, governance documents, facilities, event approvals, and product analytics.
-- Apply after club_governance.sql and club_finance.sql.
begin;
alter table public.clubs add column if not exists category text;
alter table public.clubs add column if not exists school_year text;

create table if not exists public.club_trips(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id) on delete cascade,title text not null,trip_date date not null,destination text not null,plan text not null,consent_required boolean not null default true,status text not null default 'draft' check(status in('draft','submitted','approved','rejected','completed')),submitted_by uuid not null references public.profiles(id),reviewed_by uuid references public.profiles(id),review_note text,created_at timestamptz not null default now());
create table if not exists public.trip_consents(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.club_trips(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'pending' check(status in('pending','received','declined','not_required')),updated_by uuid references public.profiles(id),updated_at timestamptz not null default now(),unique(trip_id,profile_id));
create table if not exists public.club_constitution_versions(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id) on delete cascade,version_number integer not null check(version_number>0),body text not null,change_summary text not null,adopted_on date,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(club_id,version_number));
create table if not exists public.club_elections(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id) on delete cascade,title text not null,election_date date not null,positions text[] not null default '{}',status text not null default 'planned' check(status in('planned','open','completed','cancelled')),result_summary text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.club_budgets(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id) on delete cascade,school_year text not null,allocated_cents integer not null check(allocated_cents>=0),notes text,updated_by uuid not null references public.profiles(id),updated_at timestamptz not null default now(),unique(club_id,school_year));
create table if not exists public.club_reimbursements(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id) on delete cascade,school_year text not null,amount_cents integer not null check(amount_cents>0),purpose text not null,receipt_reference text not null,status text not null default 'pending' check(status in('pending','approved','rejected','paid')),submitted_by uuid not null references public.profiles(id),reviewed_by uuid references public.profiles(id),review_note text,created_at timestamptz not null default now());
create table if not exists public.facility_permits(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs(id) on delete cascade,event_id text,title text not null,event_date date not null,start_time time,end_time time,room text,needs_security boolean not null default false,needs_library boolean not null default false,needs_av boolean not null default false,room_status text not null default 'pending',security_status text not null default 'not_required',library_status text not null default 'not_required',av_status text not null default 'not_required',overall_status text not null default 'pending' check(overall_status in('pending','approved','rejected')),submitted_by uuid not null references public.profiles(id),review_note text,created_at timestamptz not null default now());
create table if not exists public.event_approval_requests(id uuid primary key default gen_random_uuid(),club_id uuid references public.clubs(id) on delete cascade,title text not null,description text not null,start_at timestamptz not null,end_at timestamptz,location text,capacity integer check(capacity is null or capacity>0),status text not null default 'pending' check(status in('pending','approved','rejected')),submitted_by uuid not null references public.profiles(id),reviewed_by uuid references public.profiles(id),review_note text,created_at timestamptz not null default now());
create table if not exists public.event_registrations(id uuid primary key default gen_random_uuid(),approval_id uuid not null references public.event_approval_requests(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'pending' check(status in('pending','approved','waitlisted','rejected','cancelled')),reviewed_by uuid references public.profiles(id),review_note text,created_at timestamptz not null default now(),unique(approval_id,profile_id));
create table if not exists public.analytics_events(id bigint generated always as identity primary key,event_name text not null,route text,entity_id text,metric_value double precision,metadata jsonb not null default '{}',user_id uuid references public.profiles(id) on delete set null,session_id text,created_at timestamptz not null default now());
create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name,created_at desc);

do $$ declare t text; begin foreach t in array array['club_trips','trip_consents','club_constitution_versions','club_elections','club_budgets','club_reimbursements','facility_permits','event_approval_requests','event_registrations','analytics_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
drop policy if exists "Board reads trips" on public.club_trips; drop policy if exists "Board submits trips" on public.club_trips; drop policy if exists "Governors review trips" on public.club_trips;
drop policy if exists "Board manages trip consent" on public.trip_consents; drop policy if exists "Members read own trip consent" on public.trip_consents;
drop policy if exists "Board reads constitutions" on public.club_constitution_versions; drop policy if exists "Board adds constitution versions" on public.club_constitution_versions;
drop policy if exists "Board manages elections" on public.club_elections; drop policy if exists "Board reads budgets" on public.club_budgets; drop policy if exists "Governors manage budgets" on public.club_budgets;
drop policy if exists "Board manages reimbursements" on public.club_reimbursements; drop policy if exists "Board submits reimbursements" on public.club_reimbursements; drop policy if exists "Governors review reimbursements" on public.club_reimbursements;
drop policy if exists "Board manages permits" on public.facility_permits; drop policy if exists "Board submits permits" on public.facility_permits; drop policy if exists "Staff reviews permits" on public.facility_permits;
drop policy if exists "Board submits events" on public.event_approval_requests; drop policy if exists "Board and staff read events" on public.event_approval_requests; drop policy if exists "Public reads approved events" on public.event_approval_requests; drop policy if exists "Staff reviews events" on public.event_approval_requests;
drop policy if exists "Users read own registration" on public.event_registrations; drop policy if exists "Users register" on public.event_registrations; drop policy if exists "Staff reviews registrations" on public.event_registrations; drop policy if exists "Admins read analytics" on public.analytics_events;
create policy "Board reads trips" on public.club_trips for select using(public.can_manage_club(club_id));
create policy "Board submits trips" on public.club_trips for insert with check(public.can_manage_club(club_id) and submitted_by=auth.uid() and status='submitted');
create policy "Governors review trips" on public.club_trips for update using(public.can_govern_club(club_id));
create policy "Board manages trip consent" on public.trip_consents for all using(exists(select 1 from public.club_trips t where t.id=trip_id and public.can_manage_club(t.club_id))) with check(exists(select 1 from public.club_trips t where t.id=trip_id and public.can_manage_club(t.club_id)));
create policy "Members read own trip consent" on public.trip_consents for select using(profile_id=auth.uid());
create policy "Board reads constitutions" on public.club_constitution_versions for select using(public.can_manage_club(club_id));
create policy "Board adds constitution versions" on public.club_constitution_versions for insert with check(public.can_manage_club(club_id) and created_by=auth.uid());
create policy "Board manages elections" on public.club_elections for all using(public.can_manage_club(club_id)) with check(public.can_manage_club(club_id));
create policy "Board reads budgets" on public.club_budgets for select using(public.can_manage_club(club_id));
create policy "Governors manage budgets" on public.club_budgets for all using(public.can_govern_club(club_id)) with check(public.can_govern_club(club_id));
create policy "Board manages reimbursements" on public.club_reimbursements for select using(public.can_manage_club(club_id));
create policy "Board submits reimbursements" on public.club_reimbursements for insert with check(public.can_manage_club(club_id) and submitted_by=auth.uid());
create policy "Governors review reimbursements" on public.club_reimbursements for update using(public.can_govern_club(club_id));
create policy "Board manages permits" on public.facility_permits for select using(public.can_manage_club(club_id) or public.is_staff_or_admin());
create policy "Board submits permits" on public.facility_permits for insert with check(public.can_manage_club(club_id) and submitted_by=auth.uid());
create policy "Staff reviews permits" on public.facility_permits for update using(public.is_staff_or_admin());
create policy "Board submits events" on public.event_approval_requests for insert with check(public.can_manage_club(club_id) and submitted_by=auth.uid());
create policy "Board and staff read events" on public.event_approval_requests for select using(public.can_manage_club(club_id) or public.is_staff_or_admin());
create policy "Public reads approved events" on public.event_approval_requests for select using(status='approved');
create policy "Staff reviews events" on public.event_approval_requests for update using(public.is_staff_or_admin());
create policy "Users read own registration" on public.event_registrations for select using(profile_id=auth.uid() or public.is_staff_or_admin());
create policy "Users register" on public.event_registrations for insert with check(profile_id=auth.uid());
create policy "Staff reviews registrations" on public.event_registrations for update using(public.is_staff_or_admin());
create policy "Admins read analytics" on public.analytics_events for select using(public.is_admin());

create or replace function public.record_analytics_event(p_event_name text,p_route text default null,p_entity_id text default null,p_metric_value double precision default null,p_metadata jsonb default '{}',p_session_id text default null) returns void language plpgsql security definer set search_path=public as $$ begin if p_event_name not in('page_view','search_result_click','club_join_started','club_join_completed','LCP','INP','CLS') then return; end if; insert into public.analytics_events(event_name,route,entity_id,metric_value,metadata,user_id,session_id) values(p_event_name,left(p_route,300),left(p_entity_id,120),p_metric_value,coalesce(p_metadata,'{}'),auth.uid(),left(p_session_id,80)); end $$;
revoke all on function public.record_analytics_event(text,text,text,double precision,jsonb,text) from public;
grant execute on function public.record_analytics_event(text,text,text,double precision,jsonb,text) to anon,authenticated;
do $$ declare t text; begin
  if to_regprocedure('public.log_club_change()') is not null then foreach t in array array['club_trips','club_constitution_versions','club_elections','club_budgets','club_reimbursements','facility_permits','event_approval_requests'] loop execute format('drop trigger if exists audit_club_change on public.%I',t); execute format('create trigger audit_club_change after insert or update or delete on public.%I for each row execute function public.log_club_change()',t); end loop; end if;
  if to_regprocedure('public.audit_management_change()') is not null then foreach t in array array['club_trips','trip_consents','club_constitution_versions','club_elections','club_budgets','club_reimbursements','facility_permits','event_approval_requests','event_registrations'] loop execute format('drop trigger if exists %I on public.%I',t||'_global_audit',t); execute format('create trigger %I after insert or update or delete on public.%I for each row execute function public.audit_management_change()',t||'_global_audit',t); end loop; end if;
end $$;
commit;
