import Link from "next/link";
export const metadata = { title: "Privacy Policy" };
export default function PrivacyPage() {
  return <article className="mx-auto max-w-3xl space-y-6 px-5 py-10 text-sm leading-7"><h1 className="text-4xl font-bold">Privacy Policy</h1><p>Closed beta notice · Updated September 7, 2026</p>
    <section><h2 className="text-xl font-semibold">Information used by this service</h2><p>Bayside Hub processes your account email, profile name and optional avatar to identify your account. When you use community features, it stores club memberships, leadership assignments, announcements, messages, uploaded images, support requests and records of administrative changes.</p></section>
    <section><h2 className="text-xl font-semibold">Who can see your content</h2><p>Published club information, announcements and club gallery images are public. Gallery images can be accessed by anyone who has their public URL. Club chat is intended for authorized club participants and moderators; it is not end-to-end encrypted. Administrators and authorized club leaders can access information needed to manage the community. Do not post confidential student records, passwords or sensitive personal information.</p></section>
    <section><h2 className="text-xl font-semibold">Service providers and browser storage</h2><p>Supabase provides authentication, database and image storage. Vercel hosts the application, and the app includes Vercel Web Analytics. Google sign-in and Typeform feedback are optional external services with their own privacy notices. Browser cookies support authentication; local storage remembers interface preferences such as dismissal of the beta notice.</p></section>
    <section><h2 className="text-xl font-semibold">Your choices and requests</h2><p>You can sign out, avoid optional uploads, and request access, correction or deletion of account information through <Link className="underline" href="/support#technical-support">Technical Support</Link>. Specify the account and request, but never send your password. Some records may need to be retained for security, investigation or applicable school requirements; administrators should explain any exception when responding.</p></section>
    <section><h2 className="text-xl font-semibold">School review</h2><p>This beta notice describes the current application. School approval, the responsible privacy contact, retention periods and any required student or parent consent must be confirmed before wider release. An approved email address alone does not establish consent. Contact Support before submitting information if you are unsure whether you are authorized to participate.</p></section>
  </article>;
}
