import Link from "next/link";

export const metadata = { title: "Privacy Policy", description: "How Hatchx collects, uses, shares, and protects information." };

const privacySections = [
  ["Information we collect", <><p>Account and profile information may include your name, school email address, avatar, role, grade level, OSIS number, and Club invitation codes used during registration. We also process sign-in and basic device or session information needed to authenticate and secure your account.</p><p>When you use Hatchx, we may store Club memberships and leadership assignments, interests, event responses, attendance records, announcements, messages, uploaded media, support conversations, notification preferences, administrative actions, and other information you choose to submit.</p></>],
  ["How we use information", <p key="use">We use information to provide and secure accounts; personalize the platform; connect students with Clubs and opportunities; support Club operations; publish approved content; respond to support requests; send requested notifications; investigate misuse; maintain audit records; and improve reliability and usability.</p>],
  ["Who can see information", <><p>Public Club profiles, approved announcements, events, opportunities, and gallery images may be visible without signing in. Anyone with a public media URL may be able to access that file.</p><p>Club messages, rosters, attendance, operational records, and support requests are limited according to account roles and permissions, but they are not end-to-end encrypted. Authorized Club leaders, advisors, school staff, administrators, and technical operators may access information when needed to perform their responsibilities.</p></>],
  ["Service providers", <p key="providers">Hatchx uses service providers to operate the platform. Supabase provides authentication, database, and file storage services; Vercel provides hosting and web analytics; and Google may provide optional sign-in. Linked forms or websites may be operated by other providers. These services process information under their own terms and privacy practices.</p>],
  ["Cookies, local storage, and analytics", <p key="cookies">Authentication cookies keep you signed in and protect account sessions. Browser local storage may remember theme, navigation, dismissed notices, and other interface preferences. Limited analytics may collect page and performance information so we can understand use and improve the service. Hatchx does not use this information to sell personalized advertising.</p>],
  ["Retention and deletion", <p key="retention">Information is kept only as long as reasonably needed for platform operation, security, school records, dispute resolution, or applicable policy requirements. Retention periods can differ by record type. Deleting an account or item may not immediately remove backups, security logs, previously published copies, or records the school is required to retain.</p>],
  ["Security", <p key="security">We use access controls and service-provider safeguards intended to protect information. No online system can guarantee absolute security. Protect your password, sign out on shared devices, and report suspicious activity. Do not submit passwords or highly sensitive records through Club posts, chat, or support messages.</p>],
  ["Your choices and requests", <p key="choices">You may update available profile fields, choose whether to upload optional content, manage notifications, sign out, and request access, correction, or deletion through <Link href="/support#technical-support" className="font-semibold text-ink underline underline-offset-4">Technical Support</Link>. Include enough information to identify the account and request, but never send your password. Authorized administrators will explain if a request cannot be completed because of security or school record requirements.</p>],
  ["Students and school use", <p key="students">Hatchx is designed for a school community. An approved email address or invitation code does not by itself establish consent for every type of information or activity. School rules, required student or parent permissions, and applicable education-record requirements continue to apply. Ask an advisor or school administrator before submitting information if you are unsure whether it is appropriate.</p>],
  ["Policy updates and contact", <p key="updates">We may revise this policy when Hatchx features, providers, or school requirements change. The effective date below identifies the current version. For privacy questions or requests, use <Link href="/support" className="font-semibold text-ink underline underline-offset-4">Support</Link>.</p>],
];

export default function PrivacyPage() {
  return <main className="mx-auto w-full max-w-5xl px-5 py-12 sm:px-8 sm:py-16"><header className="border-b border-line pb-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-azure">Hatchx privacy</p><h1 className="mt-4 font-display text-4xl font-bold tracking-[-.04em] text-ink sm:text-6xl">Privacy Policy</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted">What information Hatchx uses, why it is needed, and the choices available to you.</p><p className="mt-6 text-xs font-semibold uppercase tracking-[.14em] text-muted">Effective October 10, 2026</p></header><div className="mt-12 grid gap-10 lg:grid-cols-[220px_1fr]"><aside><div className="sticky top-24 rounded-card border border-line bg-card p-5 text-sm"><p className="font-bold text-ink">Our approach</p><p className="mt-2 leading-6 text-muted">Collect what supports the school experience, limit access by role, and explain how the system works.</p></div></aside><article className="space-y-10">{privacySections.map(([title, content]) => <section key={String(title)}><h2 className="text-xl font-bold text-ink">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-muted">{content}</div></section>)}</article></div></main>;
}
