import Link from "next/link";

export const metadata = { title: "Terms of Use", description: "Terms governing use of the Hatchx school community platform." };

const sections = [
  ["1. Your agreement", <p key="agreement">These Terms of Use govern access to Hatchx. By using the platform, you agree to follow these terms and applicable Bayside High School and New York City Public Schools policies. If an authorized school rule or staff direction conflicts with information on Hatchx, the school rule or direction controls.</p>],
  ["2. Eligibility and accounts", <><p>Use Hatchx only with an account you are authorized to access. Student registration may require a school email address, OSIS number, grade level, or a valid Club invitation code. Provide accurate information and keep your sign-in credentials private.</p><p>You are responsible for activity performed through your account. Report suspected misuse or unauthorized access promptly through <Link href="/support" className="font-semibold text-ink underline underline-offset-4">Support</Link>. We may restrict or suspend access when necessary to protect users, school operations, or the platform.</p></>],
  ["3. Respectful and appropriate use", <><p>Use Hatchx for legitimate school-community purposes. Do not harass, threaten, impersonate, spam, disrupt the service, evade access controls, or attempt to access information beyond your permission level.</p><p>Do not submit passwords, confidential student records, highly sensitive personal information, unlawful material, or content you do not have permission to share. Photos and media may be uploaded only when required permissions have been obtained.</p></>],
  ["4. Content and moderation", <><p>You retain responsibility for content you submit. By posting content, you allow Hatchx and authorized school personnel to store, display, reproduce, and moderate it as needed to operate school-community features.</p><p>Club leaders, advisors, staff, and administrators may review, edit, decline, archive, or remove content and may change role permissions when reasonably required for accuracy, safety, policy compliance, or continuity of school operations. School-wide submissions may require approval before publication.</p></>],
  ["5. Club and leadership tools", <p key="leadership">Club-management permissions apply only to assigned organizations and responsibilities. Attendance, membership, finance, communication, and operational tools must be used for authorized school purposes. Do not export, reuse, or disclose member information outside those purposes.</p>],
  ["6. External services and links", <p key="external">Hatchx may link to third-party websites or use external services for sign-in, hosting, forms, or other functions. Their terms and privacy practices apply separately. Hatchx does not control third-party content, availability, or security.</p>],
  ["7. Availability and changes", <p key="availability">We work to keep Hatchx accurate and available, but features may change, pause, or contain errors. Confirm important deadlines, meeting details, permissions, and safety-related decisions with the responsible Club advisor or school office. We may update these terms as the platform and school requirements evolve; the date below identifies the current version.</p>],
  ["8. Safety and emergencies", <p key="safety">Hatchx is not an emergency reporting service. For an immediate safety concern, contact appropriate school staff, emergency services, or another designated reporting channel.</p>],
  ["9. Privacy and contact", <p key="privacy">Our <Link href="/privacy" className="font-semibold text-ink underline underline-offset-4">Privacy Policy</Link> explains how information is handled. Questions, account requests, and reports about these terms can be submitted through <Link href="/support" className="font-semibold text-ink underline underline-offset-4">Support</Link>.</p>],
];

export default function TermsPage() {
  return <main className="mx-auto w-full max-w-5xl px-5 py-12 sm:px-8 sm:py-16"><header className="border-b border-line pb-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-azure">Hatchx legal</p><h1 className="mt-4 font-display text-4xl font-bold tracking-[-.04em] text-ink sm:text-6xl">Terms of Use</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted">Clear expectations for using Hatchx safely, respectfully, and responsibly.</p><p className="mt-6 text-xs font-semibold uppercase tracking-[.14em] text-muted">Effective October 10, 2026</p></header><div className="mt-12 grid gap-10 lg:grid-cols-[220px_1fr]"><aside><div className="sticky top-24 rounded-card border border-line bg-card p-5 text-sm"><p className="font-bold text-ink">At a glance</p><p className="mt-2 leading-6 text-muted">Use your own account, protect private information, respect others, and follow school policy.</p></div></aside><article className="space-y-10">{sections.map(([title, content]) => <section key={String(title)}><h2 className="text-xl font-bold text-ink">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-muted">{content}</div></section>)}</article></div></main>;
}
