import { requireAdmin } from "@/lib/auth";
import { createServerClient } from "@/lib/supabase/server";
import RoleActionForm from "./forms";
const field = "min-h-11 rounded-lg border border-line bg-content-bg px-3";
export default async function RolesPage() {
  await requireAdmin();
  const db = await createServerClient();
  const [roles, assignments, clubs, profiles] = await Promise.all([
    db.from("custom_roles").select("*").order("name"), db.from("custom_role_assignments").select("*").order("created_at", { ascending: false }).limit(100),
    db.from("clubs").select("id,name").order("name"), db.from("profiles").select("id,email,full_name").limit(1000),
  ]);
  return <div className="mx-auto max-w-5xl space-y-6 px-5 py-8"><h1 className="text-3xl font-bold">Custom roles & permissions</h1><p>Create a named role, then assign it to an account. Club permissions can be restricted to one club. Only administrators may grant roles or approve school announcements.</p>{roles.error || assignments.error ? <p role="alert">Role management is unavailable until the database migration is applied.</p> : <>
    <div className="grid gap-5 md:grid-cols-2"><RoleActionForm><input type="hidden" name="operation" value="create" /><h2 className="text-xl font-semibold">Create role</h2><label className="grid gap-1">Role name<input name="name" required minLength={2} maxLength={60} className={field} /></label>{[["clubs.manage", "Edit club content, announcements and photos"], ["clubs.govern", "Manage club members and board appointments"], ["site.manage", "Edit public site text"]].map(([key, label]) => <label key={key} className="flex gap-2"><input name="permissions" value={key} type="checkbox" />{label}</label>)}<button className={field}>Create role</button></RoleActionForm>
    <RoleActionForm><input type="hidden" name="operation" value="assign" /><h2 className="text-xl font-semibold">Assign role</h2><label className="grid gap-1">Registered email<input type="email" name="email" required className={field} /></label><label className="grid gap-1">Role<select name="role_id" required className={field}>{roles.data?.map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><label className="grid gap-1">Scope<select name="club_id" className={field}><option value="">All clubs / site-wide</option>{clubs.data?.map(club => <option key={club.id} value={club.id}>{club.name}</option>)}</select></label><p className="text-xs">Site text permission requires site-wide scope.</p><button className={field}>Assign permissions</button></RoleActionForm></div>
    <h2 className="text-xl font-semibold">Current assignments</h2>{assignments.data?.map(item => <RoleActionForm key={item.id}><input type="hidden" name="operation" value="revoke" /><input type="hidden" name="id" value={item.id} /><p>{profiles.data?.find(p => p.id === item.profile_id)?.email ?? item.profile_id} · {roles.data?.find(r => r.id === item.role_id)?.name} · {clubs.data?.find(c => c.id === item.club_id)?.name ?? "Site-wide"}</p><button className={field}>Revoke assignment</button></RoleActionForm>)}
    <h2 className="text-xl font-semibold">Role definitions</h2>{roles.data?.map(role => <div key={role.id} className="space-y-2"><RoleActionForm><input type="hidden" name="operation" value="update" /><input type="hidden" name="id" value={role.id} /><label className="grid gap-1">Name<input name="name" required minLength={2} maxLength={60} defaultValue={role.name} className={field} /></label>{[["clubs.manage", "Edit club content, announcements and photos"], ["clubs.govern", "Manage members and board appointments (includes content editing)"], ["site.manage", "Edit public site text"]].map(([key, label]) => <label key={key} className="flex gap-2"><input type="checkbox" name="permissions" value={key} defaultChecked={role.permissions.includes(key)} />{label}</label>)}<p className="text-xs">Changes affect every account assigned this role, within its assigned scope.</p><button className={field}>Save definition</button></RoleActionForm><details><summary className="cursor-pointer text-sm">Remove this role</summary><RoleActionForm><input type="hidden" name="operation" value="delete" /><input type="hidden" name="id" value={role.id} /><p>Deleting {role.name} revokes all its assignments.</p><label className="flex gap-2 text-sm"><input type="checkbox" required name="confirm" value="yes" />I understand the assignments will be removed.</label><button className={field}>Delete role and revoke assignments</button></RoleActionForm></details></div>)}
  </>}</div>;
}
