"use server";
import { revalidatePath } from "next/cache";
import { getCurrentUser } from "@/lib/auth";
import { bellPeriodByNumber } from "@/lib/bell-schedule";
import { parseMoneyToCents, schoolYearIsValid } from "@/lib/club-finance";
import { parseOptionalDateOnly } from "@/lib/input-validation";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createServerClient } from "@/lib/supabase/server";

const denied={ok:false,message:"Current Club board access is required."}, invalid={ok:false,message:"Check all required fields and try again."};
async function ctx(clubId:string){const user=await getCurrentUser();if(!user||!clubId||!isSupabaseConfigured())return null;const db=await createServerClient();const [manage,govern]=await Promise.all([db.rpc("can_manage_club",{p_club_id:clubId}),db.rpc("can_govern_club",{p_club_id:clubId})]);return manage.data?{user,db,govern:govern.data===true}:null;}
const refresh=(id:string)=>revalidatePath(`/clubs/manage/${id}/operations`);

export async function createTrip(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const title=String(fd.get("title")??"").trim(),destination=String(fd.get("destination")??"").trim(),plan=String(fd.get("plan")??"").trim(),tripDate=parseOptionalDateOnly(String(fd.get("trip_date")??"")),dueAt=String(fd.get("consent_due_at")??"");if(title.length<3||destination.length<2||plan.length<10||!tripDate)return invalid;const row=await c.db.from("club_trips").insert({club_id:clubId,title,destination,plan,trip_date:tripDate,consent_required:fd.get("consent_required")==="on",status:"submitted",submitted_by:c.user.id}).select("id").maybeSingle();if(row.error||!row.data)return {ok:false,message:"Trip plan could not be submitted."};if(fd.get("consent_required")==="on"){const members=await c.db.from("club_memberships").select("profile_id").eq("club_id",clubId).eq("status","active");if(members.data?.length)await c.db.from("trip_consents").insert(members.data.map(m=>({trip_id:row.data!.id,profile_id:m.profile_id,status:"pending" as const,due_at:dueAt?new Date(dueAt).toISOString():null})));}refresh(clubId);return {ok:true,message:"Trip plan submitted and consent tracker created."};}
export async function updateConsent(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const status=String(fd.get("status")??"");if(!["pending","received","declined","not_required"].includes(status))return invalid;const result=await c.db.from("trip_consents").update({status:status as "pending"|"received"|"declined"|"not_required",updated_by:c.user.id,updated_at:new Date().toISOString()}).eq("id",String(fd.get("consent_id")??"")).select("id").maybeSingle();if(result.error||!result.data)return invalid;refresh(clubId);return {ok:true,message:"Consent status updated."};}
export async function addConstitutionVersion(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const body=String(fd.get("body")??"").trim(),summary=String(fd.get("change_summary")??"").trim(),adopted=parseOptionalDateOnly(String(fd.get("adopted_on")??""));if(body.length<50||summary.length<5||adopted===undefined)return invalid;const latest=await c.db.from("club_constitution_versions").select("version_number").eq("club_id",clubId).order("version_number",{ascending:false}).limit(1).maybeSingle();const result=await c.db.from("club_constitution_versions").insert({club_id:clubId,version_number:(latest.data?.version_number??0)+1,body,change_summary:summary,adopted_on:adopted,created_by:c.user.id});if(result.error)return {ok:false,message:"Constitution version could not be saved."};refresh(clubId);return {ok:true,message:"New constitution version saved; earlier versions remain available."};}
export async function createElection(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const title=String(fd.get("title")??"").trim(),date=parseOptionalDateOnly(String(fd.get("election_date")??"")),positions=String(fd.get("positions")??"").split(",").map(x=>x.trim()).filter(Boolean).slice(0,20);if(title.length<3||!date||!positions.length)return invalid;const {error}=await c.db.from("club_elections").insert({club_id:clubId,title,election_date:date,positions,status:"planned",created_by:c.user.id});if(error)return invalid;refresh(clubId);return {ok:true,message:"Election added to the governance timeline."};}
export async function saveBudget(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c?.govern)return {ok:false,message:"Advisor, Staff, or Admin approval is required to set a budget."};const year=String(fd.get("school_year")??""),amount=String(fd.get("allocated_amount")??"")==="0"?0:parseMoneyToCents(fd.get("allocated_amount"));if(!schoolYearIsValid(year)||amount===null)return invalid;const {error}=await c.db.from("club_budgets").upsert({club_id:clubId,school_year:year,allocated_cents:amount,notes:String(fd.get("notes")??"").trim()||null,updated_by:c.user.id,updated_at:new Date().toISOString()},{onConflict:"club_id,school_year"});if(error)return invalid;refresh(clubId);return {ok:true,message:"Budget saved."};}
export async function requestReimbursement(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const year=String(fd.get("school_year")??""),amount=parseMoneyToCents(fd.get("amount")),purpose=String(fd.get("purpose")??"").trim(),receipt=String(fd.get("receipt_reference")??"").trim(),file=fd.get("receipt_file");if(!schoolYearIsValid(year)||!amount||purpose.length<5||(!receipt&&!(file instanceof File&&file.size))||receipt.length>500)return invalid;let receiptPath:string|null=null;if(file instanceof File&&file.size){if(file.size>10_485_760||!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type))return {ok:false,message:"Receipt must be a PDF, JPG, PNG, or WebP up to 10 MB."};receiptPath=`${clubId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-").slice(-100)}`;const upload=await c.db.storage.from("club-receipts").upload(receiptPath,file,{contentType:file.type,upsert:false});if(upload.error)return {ok:false,message:"Receipt upload failed. Apply workflow_completion.sql and try again."}}const receiptLabel=receipt||(file instanceof File?file.name:"Uploaded receipt");const {error}=await c.db.from("club_reimbursements").insert({club_id:clubId,school_year:year,amount_cents:amount,purpose,receipt_reference:receiptLabel,receipt_path:receiptPath,status:"pending",submitted_by:c.user.id});if(error){if(receiptPath)await c.db.storage.from("club-receipts").remove([receiptPath]);return invalid}refresh(clubId);return {ok:true,message:"Reimbursement submitted with its private receipt."};}
export async function requestPermit(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const title=String(fd.get("title")??"").trim(),date=parseOptionalDateOnly(String(fd.get("event_date")??"")),period=bellPeriodByNumber(Number(fd.get("period")));if(title.length<3||!date||!period)return invalid;const requested=["room",...(fd.get("needs_security")==="on"?["security"]:[]),...(fd.get("needs_library")==="on"?["library"]:[]),...(fd.get("needs_av")==="on"?["av"]:[])];const assignees=new Map<string,string|null>();for(const department of requested){const email=String(fd.get(`${department}_approver_email`)??"").trim().toLowerCase();if(!email){assignees.set(department,null);continue}const profile=await c.db.from("profiles").select("id").eq("email",email).in("role",["staff","admin"]).maybeSingle();if(!profile.data)return {ok:false,message:`${department} approver must be a Staff or Admin account.`};assignees.set(department,profile.data.id)}const permit=await c.db.from("facility_permits").insert({club_id:clubId,title,event_date:date,start_time:period.startTime,end_time:period.endTime,room:String(fd.get("room")??"").trim()||null,needs_security:requested.includes("security"),needs_library:requested.includes("library"),needs_av:requested.includes("av"),room_status:"pending",security_status:requested.includes("security")?"pending":"not_required",library_status:requested.includes("library")?"pending":"not_required",av_status:requested.includes("av")?"pending":"not_required",overall_status:"pending",submitted_by:c.user.id}).select("id").maybeSingle();if(permit.error||!permit.data)return invalid;const stages=requested.map((department,index)=>({permit_id:permit.data!.id,department:department as "room"|"security"|"library"|"av",step_order:index+1,assigned_to:assignees.get(department)??null,status:"pending" as const}));const stagesResult=await c.db.from("permit_approvals").insert(stages);if(stagesResult.error)return {ok:false,message:"Permit was created, but approval stages require workflow_completion.sql."};refresh(clubId);return {ok:true,message:"Permit routed through the selected department approval sequence."};}
export async function submitEvent(fd:FormData){const clubId=String(fd.get("club_id")??"");const c=await ctx(clubId);if(!c)return denied;const title=String(fd.get("title")??"").trim(),description=String(fd.get("description")??"").trim(),start=String(fd.get("start_at")??""),end=String(fd.get("end_at")??"");const capacity=Number(fd.get("capacity")||0);if(title.length<3||description.length<10||!start||!Number.isInteger(capacity)||capacity<0)return invalid;const {error}=await c.db.from("event_approval_requests").insert({club_id:clubId,title,description,start_at:new Date(start).toISOString(),end_at:end?new Date(end).toISOString():null,location:String(fd.get("location")??"").trim()||null,capacity:capacity||null,status:"pending",submitted_by:c.user.id});if(error)return invalid;refresh(clubId);return {ok:true,message:"Event submitted for BHS approval."};}
