import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import ActionFeedbackForm from "@/components/action-feedback-form";
import { getCurrentUser } from "@/lib/auth";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createServerClient } from "@/lib/supabase/server";
import { addConstitutionVersion, createElection, createTrip, requestPermit, requestReimbursement, saveBudget, submitEvent, updateConsent } from "./actions";

const field="h-11 w-full rounded-control border border-line bg-content-bg px-3 text-sm text-ink";
const area=`${field} h-auto py-3`;
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
async function today(){return new Date().toISOString().slice(0,10);}

export default async function ClubOperationsPage({params}:{params:Promise<{id:string}>}){const user=await getCurrentUser();const {id}=await params;if(!user)redirect(`/login?next=/clubs/manage/${id}/operations`);if(!isSupabaseConfigured())redirect("/clubs/manage");const db=await createServerClient();const access=await db.rpc("can_manage_club",{p_club_id:id});if(!access.data)redirect("/clubs/manage");const [club,trips,consents,versions,elections,budgets,reimbursements,permits,events]=await Promise.all([db.from("clubs").select("id,name").eq("id",id).maybeSingle(),db.from("club_trips").select("*").eq("club_id",id).order("trip_date"),db.from("trip_consents").select("*").in("trip_id",(await db.from("club_trips").select("id").eq("club_id",id)).data?.map(x=>x.id)??["00000000-0000-0000-0000-000000000000"]),db.from("club_constitution_versions").select("*").eq("club_id",id).order("version_number",{ascending:false}),db.from("club_elections").select("*").eq("club_id",id).order("election_date",{ascending:false}),db.from("club_budgets").select("*").eq("club_id",id).order("school_year",{ascending:false}),db.from("club_reimbursements").select("*").eq("club_id",id).order("created_at",{ascending:false}),db.from("facility_permits").select("*").eq("club_id",id).order("created_at",{ascending:false}),db.from("event_approval_requests").select("*").eq("club_id",id).order("created_at",{ascending:false})]);if(!club.data)notFound();const migrationMissing=[trips,versions,elections,budgets,reimbursements,permits,events].some(x=>Boolean(x.error));const date=await today();const year=Number(date.slice(5,7))>=7?`${date.slice(0,4)}-${Number(date.slice(0,4))+1}`:`${Number(date.slice(0,4))-1}-${date.slice(0,4)}`;const consentByTrip=new Map<string,typeof consents.data>();for(const trip of trips.data??[])consentByTrip.set(trip.id,(consents.data??[]).filter(x=>x.trip_id===trip.id));return <div className="mx-auto max-w-7xl space-y-7 px-5 py-8"><div><Link href={`/clubs/manage/${id}`} className="text-sm font-semibold text-powder">← {club.data.name} workspace</Link><h1 className="mt-4 font-display text-4xl font-bold uppercase text-ink">Club Operations</h1><p className="mt-2 text-muted">Trips, consent, constitution history, elections, budgets, reimbursements, permits, and BHS event approval.</p></div>{migrationMissing&&<p role="alert" className="rounded-card border border-orange/40 bg-card p-5">Run <code>supabase/school_operations.sql</code> to enable these workflows.</p>}
<div className="grid gap-6 xl:grid-cols-2">
<Panel eyebrow="Trips" title="Trip plan & consent"><ActionFeedbackForm action={createTrip} className="grid gap-3 sm:grid-cols-2"><Hidden id={id}/><Input name="title" label="Trip name"/><Input name="destination" label="Destination"/><Input name="trip_date" label="Trip date" type="date"/><label className="flex items-center gap-2 text-sm text-ink"><input type="checkbox" name="consent_required" defaultChecked/>Parent/guardian consent required</label><label className="sm:col-span-2 text-sm text-ink">Trip plan<textarea name="plan" required minLength={10} maxLength={4000} rows={4} className={area}/></label><Submit label="Submit trip plan"/></ActionFeedbackForm><List>{trips.data?.map(t=><article key={t.id} className="rounded-control border border-line p-4"><b>{t.title}</b><p className="text-sm text-muted">{t.trip_date} · {t.destination} · {t.status}</p>{t.consent_required&&<div className="mt-3 space-y-2">{(consentByTrip.get(t.id)??[]).map((c,index)=><ActionFeedbackForm key={c.id} action={updateConsent} className="flex items-center gap-2"><Hidden id={id}/><input type="hidden" name="consent_id" value={c.id}/><span className="flex-1 text-xs text-muted">Member #{index+1}</span><select name="status" defaultValue={c.status} className="rounded-control border border-line bg-card px-2 py-1 text-sm"><option>pending</option><option>received</option><option>declined</option><option value="not_required">not required</option></select><button className="text-xs font-bold text-navy">Save</button></ActionFeedbackForm>)}</div>}</article>)}</List></Panel>
<Panel eyebrow="Governance" title="Constitution & elections"><ActionFeedbackForm action={addConstitutionVersion} className="grid gap-3"><Hidden id={id}/><Input name="change_summary" label="Amendment summary"/><Input name="adopted_on" label="Adopted date (optional)" type="date" required={false}/><label className="text-sm text-ink">Complete constitution text<textarea name="body" required minLength={50} rows={6} className={area}/></label><Submit label="Save new version"/></ActionFeedbackForm><ActionFeedbackForm action={createElection} className="mt-5 grid gap-3 border-t border-line pt-5 sm:grid-cols-2"><Hidden id={id}/><Input name="title" label="Election title"/><Input name="election_date" label="Election date" type="date"/><label className="text-sm text-ink sm:col-span-2">Positions<input name="positions" required placeholder="President, Treasurer, Secretary" className={`${field} mt-1`}/></label><Submit label="Schedule election"/></ActionFeedbackForm><List>{versions.data?.slice(0,5).map(v=><details key={v.id} className="rounded-control border border-line p-4"><summary className="cursor-pointer font-semibold">Version {v.version_number} · {v.change_summary}</summary><p className="mt-3 whitespace-pre-wrap text-sm text-muted">{v.body}</p></details>)}{elections.data?.map(e=><p key={e.id} className="rounded-control border border-line p-3 text-sm"><b>{e.title}</b> · {e.election_date} · {e.status}<span className="block text-muted">{e.positions.join(", ")}</span></p>)}</List></Panel>
<Panel eyebrow="Budget" title="Budget & reimbursement"><ActionFeedbackForm action={saveBudget} className="grid gap-3 sm:grid-cols-2"><Hidden id={id}/><Input name="school_year" label="School year" value={year}/><Input name="allocated_amount" label="Allocated amount" placeholder="1000.00"/><label className="text-sm text-ink sm:col-span-2">Budget notes<textarea name="notes" rows={3} className={area}/></label><Submit label="Save budget"/></ActionFeedbackForm><ActionFeedbackForm action={requestReimbursement} className="mt-5 grid gap-3 border-t border-line pt-5 sm:grid-cols-2"><Hidden id={id}/><Input name="school_year" label="School year" value={year}/><Input name="amount" label="Amount" placeholder="25.00"/><Input name="purpose" label="Purpose"/><Input name="receipt_reference" label="Receipt link / number"/><Submit label="Request reimbursement"/></ActionFeedbackForm><List>{budgets.data?.map(b=><p key={b.id} className="rounded-control border border-line p-3"><b>{b.school_year}: {money.format(b.allocated_cents/100)}</b><span className="block text-sm text-muted">{b.notes}</span></p>)}{reimbursements.data?.map(r=><p key={r.id} className="rounded-control border border-line p-3 text-sm"><b>{money.format(r.amount_cents/100)} · {r.purpose}</b><span className="block text-muted">{r.status} · receipt {r.receipt_reference}</span></p>)}</List></Panel>
<Panel eyebrow="Facilities" title="Building & event permits"><ActionFeedbackForm action={requestPermit} className="grid gap-3 sm:grid-cols-2"><Hidden id={id}/><Input name="title" label="Event / activity"/><Input name="event_date" label="Date" type="date"/><Input name="start_time" label="Start" type="time"/><Input name="end_time" label="End" type="time"/><Input name="room" label="Requested room" required={false}/><div className="grid gap-2 text-sm text-ink"><label><input type="checkbox" name="needs_security"/> Security</label><label><input type="checkbox" name="needs_library"/> Library</label><label><input type="checkbox" name="needs_av"/> A/V</label></div><Submit label="Request approvals"/></ActionFeedbackForm><List>{permits.data?.map(p=><p key={p.id} className="rounded-control border border-line p-3 text-sm"><b>{p.title} · {p.event_date}</b><span className="block text-muted">Overall {p.overall_status} · room {p.room_status} · security {p.security_status} · library {p.library_status} · A/V {p.av_status}</span></p>)}</List></Panel>
<Panel eyebrow="BHS Events" title="Event & registration approval"><ActionFeedbackForm action={submitEvent} className="grid gap-3 sm:grid-cols-2"><Hidden id={id}/><Input name="title" label="Event title"/><Input name="location" label="Location" required={false}/><Input name="start_at" label="Starts" type="datetime-local"/><Input name="end_at" label="Ends" type="datetime-local" required={false}/><Input name="capacity" label="Registration capacity" type="number" required={false}/><label className="text-sm text-ink sm:col-span-2">Description<textarea name="description" required minLength={10} rows={4} className={area}/></label><Submit label="Submit for BHS approval"/></ActionFeedbackForm><List>{events.data?.map(e=><p key={e.id} className="rounded-control border border-line p-3 text-sm"><b>{e.title}</b><span className="block text-muted">{e.status} · {new Date(e.start_at).toLocaleString("en-US")} · capacity {e.capacity??"open"}</span>{e.review_note&&<span className="block text-muted">{e.review_note}</span>}</p>)}</List></Panel>
</div></div>}
function Panel({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="rounded-[20px] border border-line bg-card p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-powder">{eyebrow}</p><h2 className="mb-5 mt-1 text-2xl font-bold text-ink">{title}</h2>{children}</section>}
function Hidden({id}:{id:string}){return <input type="hidden" name="club_id" value={id}/>}
function Input({name,label,type="text",required=true,value,placeholder}:{name:string;label:string;type?:string;required?:boolean;value?:string;placeholder?:string}){return <label className="text-sm text-ink">{label}<input name={name} type={type} required={required} defaultValue={value} placeholder={placeholder} className={`${field} mt-1`}/></label>}
function Submit({label}:{label:string}){return <button className="h-11 rounded-full bg-navy px-5 font-bold text-cream sm:col-span-2">{label}</button>}
function List({children}:{children:React.ReactNode}){return <div className="mt-5 space-y-3 border-t border-line pt-5">{children}</div>}
